apiVersion: v1
kind: Service
metadata:
  name: web-server
  namespace: homework
spec:
  selector:
    app.kubernetes.io/name: web-server
  type: NodePort
  ports:
  - name: web-server
    protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31800